name: Examples

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "media/**"
      - "*.md"
      - ".vscode"

jobs:
  buildtools:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Build swiftyadmin
        run: cd ./Examples/swiftyadmin && swift build -v
      - name: Build tootsdk-release
        run: cd ./Examples/tootsdk-release && swift build -v
