name: Build

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "media/**"
      - "*.md"
      - ".vscode"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
