name: Lint

on:
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - ".swift-format"
      - "**/*.swift"

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get swift version
        run: swift --version
      - name: Lint project
        run: make checklint
